repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys, --indent, "2"]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa

  # - repo: https://github.com/asottile/yesqa
  #   rev: v1.4.0
  #   hooks:
  #     - id: yesqa
  #       additional_dependencies: &flake8_deps
  #         - flake8-annotations==2.9.0
  #         - flake8-broken-line==0.5.0
  #         - flake8-bugbear==22.7.1
  #         - flake8-comprehensions==3.10.0
  #         - flake8-eradicate==1.3.0
  #         - flake8-quotes==3.3.1
  #         - flake8-simplify==0.19.3
  #         - flake8-tidy-imports==4.8.0
  #         - flake8-type-checking==2.1.2
  #         - flake8-typing-imports==1.12.0
  #         - flake8-use-fstring==1.4
  #         - pep8-naming==0.13.1

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus, --keep-runtime-typing]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--all]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "isort (python)"
        types: [python]
        args: [--add-import, from __future__ import annotations]
        exclude: |
          (?x)(
             ^(install|get)-poetry.py$
              | ^tls_client/__init__.py$
          )
      - id: isort
        name: "isort (pyi)"
        types: [pyi]
        args: [--lines-after-imports, "-1"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming
          - flake8-comprehensions
          - flake8-annotations
          - flake8-quotes
          - flake8-simplify
          - flake8-tidy-imports
          # - flake8-type-checking
          - flake8-use-fstring
          - flake8-typing-imports
          # - flake8-docstrings
          - flake8-isort
          - flake8-bandit

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.0.4
    hooks:
      - id: validate_manifest

  # - repo: local
  #   hooks:
  #     # - id: autoflake
  #     #   name: autoflake
  #     #   entry: poetry run autoflake -r -i --remove-all-unused-imports --remove-unused-variables
  #     #   language: system
  #     #   types: [ python ]
  #     # - id: isort
  #     #   name: isort
  #     #   entry: poetry run isort
  #     #   language: system
  #     #   types: [python]
  #     # - id: black
  #     #   name: black
  #     #   entry: poetry run black
  #     #   language: system
  #     #   types: [python]
  #     # - id: pyupgrade
  #     #   name: pyupgrade
  #     #   entry: poetry run pyupgrade --py37-plus
  #     #   language: system
  #     #   types: [python]
  #     - id: mypy
  #       name: mypy
  #       entry: poetry run mypy .
  #       require_serial: true
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #     # - id: flake8
  #     #   name: flake8
  #     #   entry: poetry run flake8
  #     #   language: system
  #     #   types: [python]
  #     - id: kacl-verify
  #       name: kacl-verify
  #       entry: poetry run kacl-cli verify
  #       language: system
  #       files: 'CHANGELOG.md'
  #       pass_filenames: false
  # - repo: https://github.com/python-poetry/poetry
  #   rev: "1.1.14"
  #   hooks:
  #     - id: poetry-check
  #     - id: poetry-lock
  #     - id: poetry-export
  #       args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry-check
        description: run poetry check to validate config
        entry: poetry check
        language: python
        language_version: python3
        pass_filenames: false
        files: ^pyproject.toml$

      - id: poetry-lock
        name: poetry-lock
        description: run poetry lock to update lock file
        entry: poetry lock
        language: python
        language_version: python3
        pass_filenames: false
        files: ^pyproject.toml$

      - id: poetry-export
        name: poetry-export
        description: run poetry export to sync lock file with requirements.txt
        entry: poetry export
        language: python
        language_version: python3
        pass_filenames: false
        files: ^poetry.lock$
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
